# Generated by Django 2.2.4 on 2019-08-17 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='References',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Subject name')),
                ('books', models.TextField(null=True)),
                ('web', models.TextField(null=True, verbose_name='Web Sources')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Subject Name')),
                ('department', models.CharField(choices=[('CSE', 'Computer Science'), ('ECE', 'Electronics and Communication'), ('IT', 'Information Technology')], max_length=4, verbose_name='Department')),
                ('year', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], verbose_name='Year')),
                ('semester', models.IntegerField(choices=[(1, 1), (2, 2)], verbose_name='Semester')),
                ('unit_1', models.TextField()),
                ('unit_2', models.TextField()),
                ('unit_3', models.TextField()),
                ('unit_4', models.TextField()),
                ('unit_5', models.TextField()),
            ],
        ),
    ]
