# Generated by Django 2.2.4 on 2019-08-17 04:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courseinformation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('CSE', 'Computer Science'), ('ECE', 'Electronics and Communication'), ('IT', 'Information Technology')], max_length=4, verbose_name='Department')),
                ('year', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], verbose_name='Year')),
                ('semester', models.IntegerField(choices=[(1, 1), (2, 2)], verbose_name='Semester')),
                ('user', models.ForeignKey(default=1, on_delete='CASCADE', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
