# Generated by Django 2.2.4 on 2019-08-17 04:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseinformation', '0002_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(default=1, on_delete='CASCADE', to=settings.AUTH_USER_MODEL),
        ),
    ]
