# Generated by Django 2.2.4 on 2019-08-17 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseinformation', '0005_subject_subjectid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='subjectid',
        ),
    ]
