# Generated by Django 2.2.4 on 2019-08-17 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseinformation', '0006_remove_subject_subjectid'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='subjectid',
            field=models.IntegerField(default=0, verbose_name='Subject ID'),
        ),
    ]
