# Generated by Django 2.2.4 on 2019-08-17 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseinformation', '0007_subject_subjectid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subjectid',
            field=models.IntegerField(default=0, unique=True, verbose_name='Subject ID'),
        ),
    ]
