# Generated by Django 2.2.4 on 2019-08-17 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseinformation', '0008_auto_20190817_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='references',
            name='subjectid',
            field=models.IntegerField(default=0, unique=True, verbose_name='Subject ID'),
        ),
    ]
